services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: es01
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9302:9302"
    volumes:
      - es-data-es01:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
  
  api:
    build: ./api
    container_name: api
    depends_on:
      es01:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOST=http://es01:9200
    ports:
      - "8000:8000"
    volumes:
      - models:/api/models
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.panucci.cloud`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=web"
      - "traefik.http.services.api.loadbalancer.server.port=8000"

      # ratelimits to avoid ddos since api is public
      - "traefik.http.middlewares.api-ratelimit.ratelimit.average=30"
      - "traefik.http.middlewares.api-ratelimit.ratelimit.burst=50"
      - "traefik.http.routers.api.middlewares=api-ratelimit"
  
  db:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stiigp -d recsys || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://api.panucci.cloud
    container_name: frontend
    depends_on:
      api:
        condition: service_started
    ports:
      - "3000:80"
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"

      # Roteador: host + path
      - "traefik.http.routers.frontend.rule=Host(`recsys.panucci.cloud`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=lets-encrypt"
      - "traefik.docker.network=web"

      # Serviço apontando pra porta interna do Vue
      - "traefik.http.services.frontend.loadbalancer.server.port=80"


volumes:
  es-data-es01:
  pgdata:
  models:

networks:
  web:
    external: true    
  default:
    driver: bridge
